import { format } from "../src/formatter/ios";
import { strict as assert } from "assert";

const defaultOptions = {
  convertPlaceholders: false,
  stripPlatformPostfixes: false,
};

describe("iOS formatter", () => {
  it("should format text as iOS .strings", () => {
    let expected = `// This file was generated by localeasy.

/* comment1 */
"key1" = "translation1";

/* comment2 */
"key2" = "translation2";`;

    let actual = format(
      [
        {
          key: "key1",
          comment: "comment1",
          translation: "translation1",
          locale: "en",
        },
        {
          key: "key2",
          comment: "comment2",
          translation: "translation2",
          locale: "en",
        },
      ],
      defaultOptions,
    );

    assert.equal(actual, expected);
  });

  it("should not include empty comments", () => {
    let expected = `// This file was generated by localeasy.

"key" = "translation";`;

    let actual = format([{
      key: "key",
      translation: "translation",
      locale: "en",
    }], defaultOptions);
    assert.equal(actual, expected);
  });

  it("should skip android specific translations", () => {
    let expected = `// This file was generated by localeasy.

/* comment */
"key" = "translation";

/* comment */
"my_android_key" = "translation";`;

    const input = [
      {
        key: "key",
        comment: "comment",
        translation: "translation",
        locale: "en",
      },
      {
        key: "my_android_key",
        comment: "comment",
        translation: "translation",
        locale: "en",
      },
      {
        key: "key_android",
        comment: "comment",
        translation: "translation",
        locale: "en",
      },
    ];

    let actual = format(input, defaultOptions);

    assert.equal(actual, expected);
  });

  it("should strip _ios plaform postfix when stripPlatformPostfixes is true", () => {
    let expected = `// This file was generated by localeasy.

/* comment */
"key" = "translation";`;

    const input = [{
      key: "key_ios",
      comment: "comment",
      translation: "translation",
      locale: "en",
    }];

    let actual = format(input, {
      ...defaultOptions,
      stripPlatformPostfixes: true,
    });

    assert.equal(actual, expected);
  });

  it("should not strip _ios plaform postfix when stripPlatformPostfixes is false", () => {
    let expected = `// This file was generated by localeasy.

/* comment */
"key_ios" = "translation";`;

    const input = [{
      key: "key_ios",
      comment: "comment",
      translation: "translation",
      locale: "en",
    }];

    let actual = format(input, defaultOptions);

    assert.equal(actual, expected);
  });

  it("should escape special characters", () => {
    let expected = `// This file was generated by localeasy.

"key" = "Good \\"morning\\"";

"key2" = "Hello \\n there";

"key3" = "Hello \\n there";`;

    const input = [
      { key: "key", translation: 'Good "morning"', locale: "en" },
      { key: "key2", translation: "Hello \\n there", locale: "en" },
      { key: "key3", translation: "Hello \n there", locale: "en" },
    ];

    let actual = format(input, defaultOptions);

    assert.equal(actual, expected);
  });

  it("should not convert placeholders when the convertPlaceholders option is false", () => {
    let expected = `// This file was generated by localeasy.

"key" = "Welcome %s";`;

    const input = [{ key: "key", translation: "Welcome %s", locale: "en" }];

    let actual = format(input, defaultOptions);

    assert.equal(actual, expected);
  });

  it("should convert placeholders when the convertPlaceholders option is true", () => {
    let expected = `// This file was generated by localeasy.

"key" = "Welcome %@";`;

    const input = [{ key: "key", translation: "Welcome %s", locale: "en" }];

    let actual = format(input, {
      ...defaultOptions,
      convertPlaceholders: true,
    });

    assert.equal(actual, expected);
  });

  it("should sort translations by key", () => {
    const expected = `// This file was generated by localeasy.

"0" = "translation";

"1" = "translation";

"99" = "translation";

"A" = "translation";

"a" = "translation";

"B" = "translation";

"b" = "translation";`;

    const actual = format(
      [
        {
          key: "B",
          comment: undefined,
          translation: "translation",
          locale: "en",
        },
        {
          key: "A",
          comment: undefined,
          translation: "translation",
          locale: "en",
        },
        {
          key: "99",
          comment: undefined,
          translation: "translation",
          locale: "en",
        },
        {
          key: "b",
          comment: undefined,
          translation: "translation",
          locale: "en",
        },
        {
          key: "1",
          comment: undefined,
          translation: "translation",
          locale: "en",
        },
        {
          key: "a",
          comment: undefined,
          translation: "translation",
          locale: "en",
        },
        {
          key: "0",
          comment: undefined,
          translation: "translation",
          locale: "en",
        },
      ],
      defaultOptions,
    );

    assert.equal(actual, expected);
  });
});
