import { assertEquals } from "../dev_deps.ts";
import { input } from "./fixtures/input.ts";
import { format } from "../src/formatter/ios.ts";

const defaultOptions = {
  convertPlaceholders: true,
  stripPlatformSuffixes: true,
};

Deno.test("should format text as iOS .strings", () => {
  const expected = `// This file was generated by localeasy.

"only" = "Translation only iOS";

/* comment */
"with_comment" = "Translation with comment";

"with_escaped_newline" = "With escaped \\n newline";

"with_newline" = "With \\n newline";

"with_placeholder" = "Translation %@ with placeholder";

"with_placeholder_escaped" = "Translation %%s with escaped placeholder";

"with_placeholder_only" = "Translation %s with placeholder only ios";

"with_quotes" = "With \\"quotes\\"";

"without_comment" = "Translation without comment";`;

  const actual = format(input, defaultOptions);

  assertEquals(actual, expected);
});
