import { FormattingOptions, Translation } from "../interfaces.ts";
import { sortTranslations } from "../utils/sort.ts";

export function format(
  translations: Translation[],
  options: FormattingOptions,
) {
  const rows = sortTranslations(translations)
    .map((e) => formatTranslation(e, options))
    .filter((e) => !!e)
    .join("\n\n");

  return [
    "// This file was generated by localeasy",
    "// https://github.com/wvteijlingen/localeasy",
    "",
    rows,
    "", // Add trailing newline to the generated file
  ].join("\n");
}

function formatTranslation(
  { comment, key, translation }: Translation,
  options: FormattingOptions,
) {
  let isPlatformSpecific = false;

  if (key.endsWith("_android")) {
    return null;
  } else if (options.stripPlatformSuffixes && key.endsWith("_ios")) {
    isPlatformSpecific = true;
    key = key.slice(0, -4);
  }

  const normalizedKey = escapeSpecialCharacters(key);
  let normalizedTranslation = escapeSpecialCharacters(translation);

  if (options.convertPlaceholders && !isPlatformSpecific) {
    normalizedTranslation = convertPlaceholders(normalizedTranslation);
  }

  return [
    comment ? `/* ${comment} */` : undefined,
    `"${normalizedKey}" = "${normalizedTranslation}";`,
  ]
    .filter((e) => !!e)
    .join("\n");
}

function escapeSpecialCharacters(input: string): string {
  return input.replace(/\"/g, '\\"').replace(/\n/g, "\\n");
}

function convertPlaceholders(input: string): string {
  return input.replace(/([^%])%s/g, (_, capture) => `${capture}%@`);
}
